/**
 * Generated by apidoc - http://www.apidoc.me
 * Service version: 0.0.1-dev
 * apidoc:0.8.14 http://www.apidoc.me/infomofo/oroku/0.0.1-dev/scala_models
 */
package com.infomofo.oroku.v0.models

/**
   * Information provided to show a smart app banner to direct the user to an
   * equivalent app store listing when viewing this webpage on iOS.  See
   * https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html
   */
  case class AppleItunesMetadata(
    appId: com.infomofo.oroku.v0.models.MetaInteger,
    affiliateData: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    appArgument: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * A brand is a name used by an organization or business person for labeling a
   * product, product group, or similar.
   */
  case class BrandObject(
    logo: _root_.scala.Option[String] = None,
    name: _root_.scala.Option[String] = None
  )

  /**
   * Extracted metadata based on common webpage and article publishing conventions,
   * roughly based on Readability and Goose https://github.com/jiminoc/goose/wiki
   */
  case class ExtractedMetadata(
    text: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    images: Seq[com.infomofo.oroku.v0.models.MediaObject],
    description: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * A media type specified by open graph. The og:image, og:audio, and og:video
   * property has some optional structured properties.
   */
  case class MediaObject(
    url: com.infomofo.oroku.v0.models.MetaString,
    secureUrl: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    mimeType: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    width: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaInteger] = None,
    height: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaInteger] = None
  )

  /**
   * An html head meta tag that has been parsed for boolean content.
   */
  case class MetaBoolean(
    value: Boolean,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for date time content.
   */
  case class MetaDateTimeIso8601(
    value: _root_.org.joda.time.DateTime,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for decimal content.
   */
  case class MetaDecimal(
    value: BigDecimal,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for integer content.
   */
  case class MetaInteger(
    value: Int,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for open_graph_type content.
   */
  case class MetaOpenGraphType(
    value: com.infomofo.oroku.v0.models.OpenGraphType,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for string content.
   */
  case class MetaString(
    value: String,
    tag: String
  )

  /**
   * An html head meta tag that has been parsed for twitter_card_type content.
   */
  case class MetaTwitterCardType(
    value: com.infomofo.oroku.v0.models.TwitterCardType,
    tag: String
  )

  /**
   * Information about the site presented in opengraph format (see ogp.me)
   */
  case class OpenGraphMetadata(
    title: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    openGraphType: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaOpenGraphType] = None,
    image: _root_.scala.Option[com.infomofo.oroku.v0.models.MediaObject] = None,
    url: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    description: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    determiner: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    locale: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    localeAlternative: Seq[com.infomofo.oroku.v0.models.MetaString] = Nil,
    siteName: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    video: _root_.scala.Option[com.infomofo.oroku.v0.models.MediaObject] = None,
    audio: _root_.scala.Option[com.infomofo.oroku.v0.models.MediaObject] = None,
    updatedTime: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaDateTimeIso8601] = None,
    seeAlso: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    appId: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    profileId: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    salePrice: _root_.scala.Option[com.infomofo.oroku.v0.models.Price] = None,
    price: _root_.scala.Option[com.infomofo.oroku.v0.models.Price] = None,
    originalPrice: _root_.scala.Option[com.infomofo.oroku.v0.models.Price] = None
  )

  /**
   * The basic information on this webpage, according to major metadata tagging
   * standards and conventions, as well as information derived from the content of
   * the page itself.
   */
  case class PageInfo(
    titles: Seq[String],
    images: Seq[String],
    descriptions: Seq[String],
    urls: Seq[String],
    keywords: Seq[String],
    categories: Seq[String],
    locations: Seq[String],
    prices: Seq[com.infomofo.oroku.v0.models.Price],
    retrievedAt: _root_.org.joda.time.DateTime,
    site: com.infomofo.oroku.v0.models.Site,
    openGraphMetadata: _root_.scala.Option[com.infomofo.oroku.v0.models.OpenGraphMetadata] = None,
    appleItunesMetadata: _root_.scala.Option[com.infomofo.oroku.v0.models.AppleItunesMetadata] = None,
    twitterCardMetadata: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterCardMetadata] = None,
    schemaOrgItems: Seq[com.infomofo.oroku.v0.models.SchemaOrgItem] = Nil,
    searchMetadata: _root_.scala.Option[com.infomofo.oroku.v0.models.SearchMetadata] = None,
    extractedMetadata: _root_.scala.Option[com.infomofo.oroku.v0.models.ExtractedMetadata] = None
  )

  /**
   * A price for a product on this page
   */
  case class Price(
    amount: com.infomofo.oroku.v0.models.MetaDecimal,
    currency: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * The representation of an item according to schema.org. schema.org is a
   * collaboration by Google, Microsoft, and Yahoo! to improve the web by creating a
   * structured data markup schema supported by major search engines. Multiple item
   * scopes can be included on one page.  Only the most common properties are
   * currently parsed. See: http://schema.org/docs/gs.html.
   */
  case class SchemaOrgItem(
    itemType: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    name: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    alternateName: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    description: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    image: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    url: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    sameAs: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    brand: _root_.scala.Option[com.infomofo.oroku.v0.models.BrandObject] = None,
    color: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    productId: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    sku: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    model: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    gtin8: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    gtin13: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    gtin14: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * Meta tags provide search engines with information about their sites. Meta tags
   * can be used to provide information to all sorts of clients, and each system
   * processes only the meta tags they understand and ignores the rest.  See
   * https://support.google.com/webmasters/answer/79812?hl=en.
   */
  case class SearchMetadata(
    description: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    title: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    robots: Seq[com.infomofo.oroku.v0.models.MetaString] = Nil,
    googlebot: Seq[com.infomofo.oroku.v0.models.MetaString] = Nil,
    googleSiteLinkSearchBox: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaBoolean] = None,
    googleNotranslate: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaBoolean] = None,
    googleSiteVerification: Seq[com.infomofo.oroku.v0.models.MetaString] = Nil,
    charset: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    contentType: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    keywords: Seq[com.infomofo.oroku.v0.models.MetaString] = Nil
  )

  /**
   * information about the domain that this site is hosted on.
   */
  case class Site(
    name: String,
    siteType: _root_.scala.Option[String] = None,
    domain: _root_.scala.Option[String] = None
  )

  /**
   * A twitter card to detail a mobile app with direct download.
   */
  case class TwitterAppInfo(
    country: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    iphone: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterAppStoreInfo] = None,
    ipad: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterAppStoreInfo] = None,
    googleplay: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterAppStoreInfo] = None
  )

  /**
   * Information linking twitter card data to an app store. See
   * https://dev.twitter.com/cards/types/app
   */
  case class TwitterAppStoreInfo(
    id: com.infomofo.oroku.v0.models.MetaString,
    name: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    url: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * Additinal information provided by a webpage to control how a link to that page
   * is rendered when posted on twitter. See also:
   * https://dev.twitter.com/cards/markup.
   */
  case class TwitterCardMetadata(
    images: Seq[com.infomofo.oroku.v0.models.MediaObject],
    card: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaTwitterCardType] = None,
    url: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    domain: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    site: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterUser] = None,
    creator: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterUser] = None,
    description: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    title: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    app: _root_.scala.Option[com.infomofo.oroku.v0.models.TwitterAppInfo] = None,
    customFields: Seq[com.infomofo.oroku.v0.models.TwitterCustomField] = Nil
  )

  /**
   * A customizable data field to display on a twitter card
   */
  case class TwitterCustomField(
    data: com.infomofo.oroku.v0.models.MetaString,
    label: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None
  )

  /**
   * User info declared for parsing into a twitter card.  See:
   * https://dev.twitter.com/cards/markup
   */
  case class TwitterUser(
    username: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaString] = None,
    id: _root_.scala.Option[com.infomofo.oroku.v0.models.MetaInteger] = None
  )

  /**
   * The type of your object according to the open graph protocol.  When the
   * community agrees on the schema for a type, it is added to the list of global
   * types. All other objects in the type system are CURIEs of the form.
   */
  sealed trait OpenGraphType

  object OpenGraphType {

    case object Article extends OpenGraphType { override def toString = "article" }
    case object Book extends OpenGraphType { override def toString = "book" }
    case object Profile extends OpenGraphType { override def toString = "profile" }
    case object Website extends OpenGraphType { override def toString = "website" }

    /**
     * UNDEFINED captures values that are sent either in error or
     * that were added by the server after this library was
     * generated. We want to make it easy and obvious for users of
     * this library to handle this case gracefully.
     *
     * We use all CAPS for the variable name to avoid collisions
     * with the camel cased values above.
     */
    case class UNDEFINED(override val toString: String) extends OpenGraphType

    /**
     * all returns a list of all the valid, known values. We use
     * lower case to avoid collisions with the camel cased values
     * above.
     */
    val all = Seq(Article, Book, Profile, Website)

    private[this]
    val byName = all.map(x => x.toString -> x).toMap

    def apply(value: String): OpenGraphType = fromString(value).getOrElse(UNDEFINED(value))

    def fromString(value: String): _root_.scala.Option[OpenGraphType] = byName.get(value)

  }

  /**
   * The card type specified for this page that will affect how a link to this page
   * will be rendered if posted on twitter. See: https://dev.twitter.com/cards/types.
   */
  sealed trait TwitterCardType

  object TwitterCardType {

    /**
     * Default Card, including a title, description, thumbnail, and Twitter account
     * attribution. See https://dev.twitter.com/cards/types/summary.
     */
    case object Summary extends TwitterCardType { override def toString = "summary" }
    /**
     * Similar to a Summary Card, but with a prominently featured image. See
     * https://dev.twitter.com/cards/types/summary-large-image
     */
    case object SummaryLargeImage extends TwitterCardType { override def toString = "summary_large_image" }
    /**
     * A Card with a photo only. See https://dev.twitter.com/cards/types/photo.
     */
    case object Photo extends TwitterCardType { override def toString = "photo" }
    /**
     * A Card highlighting a collection of four photos. See
     * https://dev.twitter.com/cards/types/gallery
     */
    case object Gallery extends TwitterCardType { override def toString = "gallery" }
    /**
     * A Card to detail a mobile app with direct download.  See
     * https://dev.twitter.com/cards/types/app
     */
    case object App extends TwitterCardType { override def toString = "app" }
    /**
     * A Card to provide video/audio/media. See
     * https://dev.twitter.com/cards/types/player
     */
    case object Player extends TwitterCardType { override def toString = "player" }
    /**
     * A Card optimized for product information. See
     * https://dev.twitter.com/cards/types/product.
     */
    case object Product extends TwitterCardType { override def toString = "product" }

    /**
     * UNDEFINED captures values that are sent either in error or
     * that were added by the server after this library was
     * generated. We want to make it easy and obvious for users of
     * this library to handle this case gracefully.
     *
     * We use all CAPS for the variable name to avoid collisions
     * with the camel cased values above.
     */
    case class UNDEFINED(override val toString: String) extends TwitterCardType

    /**
     * all returns a list of all the valid, known values. We use
     * lower case to avoid collisions with the camel cased values
     * above.
     */
    val all = Seq(Summary, SummaryLargeImage, Photo, Gallery, App, Player, Product)

    private[this]
    val byName = all.map(x => x.toString -> x).toMap

    def apply(value: String): TwitterCardType = fromString(value).getOrElse(UNDEFINED(value))

    def fromString(value: String): _root_.scala.Option[TwitterCardType] = byName.get(value)

  }